#ifndef PDS_ALIAS_DDL_H
#define PDS_ALIAS_DDL_H 1

// *** Do not edit this file, it is auto-generated ***

#include <vector>
#include <iosfwd>
#include <cstddef>
#include "pdsdata/xtc/TypeId.hh"
#include "ndarray/ndarray.h"
#include "pdsdata/xtc/SrcAlias.hh"
namespace Pds {
namespace Alias {

/** @class ConfigV1

  
*/


class ConfigV1 {
public:
  enum { TypeId = Pds::TypeId::Id_AliasConfig /**< XTC type ID value (from Pds::TypeId class) */ };
  enum { Version = 1 /**< XTC type version number */ };
  ConfigV1()
  {
  }
  ConfigV1(uint32_t arg__numSrcAlias, const Pds::SrcAlias* arg__srcAlias);
  ConfigV1(const ConfigV1& other) {
    const char* src = reinterpret_cast<const char*>(&other);
    std::copy(src, src+other._sizeof(), reinterpret_cast<char*>(this));
  }
  ConfigV1& operator=(const ConfigV1& other) {
    const char* src = reinterpret_cast<const char*>(&other);
    std::copy(src, src+other._sizeof(), reinterpret_cast<char*>(this));
    return *this;
  }
  /** Number of alias definitions */
  uint32_t numSrcAlias() const { return _numSrcAlias; }
  /** SrcAlias configuration objects

    Note: this overloaded method accepts shared pointer argument which must point to an object containing
    this instance, the returned ndarray object can be used even after this instance disappears. */
  template <typename T>
  ndarray<const Pds::SrcAlias, 1> srcAlias(const boost::shared_ptr<T>& owner) const { 
    ptrdiff_t offset=4;
    const Pds::SrcAlias* data = (const Pds::SrcAlias*)(((char*)this)+offset);
    return make_ndarray(boost::shared_ptr<const Pds::SrcAlias>(owner, data), this->numSrcAlias());
  }
  /** SrcAlias configuration objects

    Note: this method returns ndarray instance which does not control lifetime
    of the data, do not use returned ndarray after this instance disappears. */
  ndarray<const Pds::SrcAlias, 1> srcAlias() const { ptrdiff_t offset=4;
  const Pds::SrcAlias* data = (const Pds::SrcAlias*)(((char*)this)+offset);
  return make_ndarray(data, this->numSrcAlias()); }
  uint32_t _sizeof() const { return ((((4+(40*(this->numSrcAlias())))+4)-1)/4)*4; }
private:
  uint32_t	_numSrcAlias;	/**< Number of alias definitions */
  //Pds::SrcAlias	_srcAlias[this->numSrcAlias()];
};
} // namespace Alias
} // namespace Pds
#endif // PDS_ALIAS_DDL_H
