#ifndef PDS_JUNGFRAU_DDL_H
#define PDS_JUNGFRAU_DDL_H 1

// *** Do not edit this file, it is auto-generated ***

#include <vector>
#include <iosfwd>
#include <cstddef>
#include <cstring>
#include "pdsdata/xtc/TypeId.hh"
#include "ndarray/ndarray.h"
namespace Pds {
namespace Jungfrau {

/** @class ConfigV1

  
*/

#pragma pack(push,4)

class ConfigV1 {
public:
  enum { TypeId = Pds::TypeId::Id_JungfrauConfig /**< XTC type ID value (from Pds::TypeId class) */ };
  enum { Version = 1 /**< XTC type version number */ };
  enum GainMode {
    Normal = 0,
    FixedGain1 = 1,
    FixedGain2 = 2,
    ForcedGain1 = 3,
    ForcedGain2 = 4,
    HighGain0 = 5,
  };
  enum SpeedMode {
    Quarter = 0,
    Half = 1,
  };
  ConfigV1(uint32_t arg__numberOfModules, uint32_t arg__numberOfRowsPerModule, uint32_t arg__numberOfColumnsPerModule, uint32_t arg__biasVoltage, Jungfrau::ConfigV1::GainMode arg__gainMode, Jungfrau::ConfigV1::SpeedMode arg__speedMode, double arg__triggerDelay, double arg__exposureTime);
  ConfigV1() {}
  ConfigV1(const ConfigV1& other) {
    const char* src = reinterpret_cast<const char*>(&other);
    std::copy(src, src+other._sizeof(), reinterpret_cast<char*>(this));
  }
  ConfigV1& operator=(const ConfigV1& other) {
    const char* src = reinterpret_cast<const char*>(&other);
    std::copy(src, src+other._sizeof(), reinterpret_cast<char*>(this));
    return *this;
  }
  /** The number of modules in a physical camera. */
  uint32_t numberOfModules() const { return _numberOfModules; }
  /** The number of rows per module. */
  uint32_t numberOfRowsPerModule() const { return _numberOfRowsPerModule; }
  /** The number of columns per module. */
  uint32_t numberOfColumnsPerModule() const { return _numberOfColumnsPerModule; }
  /** The bias applied to the sensor in volts. */
  uint32_t biasVoltage() const { return _biasVoltage; }
  /** The gain mode set for the camera. */
  Jungfrau::ConfigV1::GainMode gainMode() const { return Jungfrau::ConfigV1::GainMode(_gainMode); }
  /** The camera clock speed setting. */
  Jungfrau::ConfigV1::SpeedMode speedMode() const { return Jungfrau::ConfigV1::SpeedMode(_speedMode); }
  /** Internal delay from receiving a trigger input until the start of an acquisiton in seconds. */
  double triggerDelay() const { return _triggerDelay; }
  /** The exposure time in seconds. */
  double exposureTime() const { return _exposureTime; }
  /** Total size in bytes of the Frame object */
  uint32_t frameSize() const;
  /** calculate total frame size in pixels based on the current ROI and binning settings */
  uint32_t numPixels() const { return numberOfModules()*numberOfRowsPerModule()*numberOfColumnsPerModule(); }
  static uint32_t _sizeof() { return 36; }
private:
  uint32_t	_numberOfModules;	/**< The number of modules in a physical camera. */
  uint32_t	_numberOfRowsPerModule;	/**< The number of rows per module. */
  uint32_t	_numberOfColumnsPerModule;	/**< The number of columns per module. */
  uint32_t	_biasVoltage;	/**< The bias applied to the sensor in volts. */
  uint16_t	_gainMode;	/**< The gain mode set for the camera. */
  uint16_t	_speedMode;	/**< The camera clock speed setting. */
  double	_triggerDelay;	/**< Internal delay from receiving a trigger input until the start of an acquisiton in seconds. */
  double	_exposureTime;	/**< The exposure time in seconds. */
};
std::ostream& operator<<(std::ostream& str, Jungfrau::ConfigV1::GainMode enval);
std::ostream& operator<<(std::ostream& str, Jungfrau::ConfigV1::SpeedMode enval);
#pragma pack(pop)

/** @class ElementV1

  
*/

class ConfigV1;
#pragma pack(push,2)

class ElementV1 {
public:
  enum { TypeId = Pds::TypeId::Id_JungfrauElement /**< XTC type ID value (from Pds::TypeId class) */ };
  enum { Version = 1 /**< XTC type version number */ };
  ElementV1() {}
private:
  ElementV1(const ElementV1&);
  ElementV1& operator=(const ElementV1&);
public:
  /** The internal frame counter number of the detector. */
  uint32_t frameNumber() const { return _frameNumber; }
  /** The LCLS timing tick associated with the detector frame. */
  uint32_t ticks() const { return _ticks; }
  /** The LCLS timing fiducial associated with the detector frame. */
  uint32_t fiducials() const { return _fiducials; }
  /**     Note: this overloaded method accepts shared pointer argument which must point to an object containing
    this instance, the returned ndarray object can be used even after this instance disappears. */
  template <typename T>
  ndarray<const uint16_t, 3> frame(const Jungfrau::ConfigV1& cfg, const boost::shared_ptr<T>& owner) const { 
    ptrdiff_t offset=12;
    const uint16_t* data = (const uint16_t*)(((char*)this)+offset);
    return make_ndarray(boost::shared_ptr<const uint16_t>(owner, data), cfg.numberOfModules(), cfg.numberOfRowsPerModule(), cfg.numberOfColumnsPerModule());
  }
  /**     Note: this method returns ndarray instance which does not control lifetime
    of the data, do not use returned ndarray after this instance disappears. */
  ndarray<const uint16_t, 3> frame(const Jungfrau::ConfigV1& cfg) const { ptrdiff_t offset=12;
  const uint16_t* data = (const uint16_t*)(((char*)this)+offset);
  return make_ndarray(data, cfg.numberOfModules(), cfg.numberOfRowsPerModule(), cfg.numberOfColumnsPerModule()); }
  static uint32_t _sizeof(const Jungfrau::ConfigV1& cfg) { return ((((12+(2*(cfg.numberOfModules())*(cfg.numberOfRowsPerModule())*(cfg.numberOfColumnsPerModule())))+2)-1)/2)*2; }
private:
  uint32_t	_frameNumber;	/**< The internal frame counter number of the detector. */
  uint32_t	_ticks;	/**< The LCLS timing tick associated with the detector frame. */
  uint32_t	_fiducials;	/**< The LCLS timing fiducial associated with the detector frame. */
  //uint16_t	_frame[cfg.numberOfModules()][cfg.numberOfRowsPerModule()][cfg.numberOfColumnsPerModule()];
};
#pragma pack(pop)
} // namespace Jungfrau
} // namespace Pds
#endif // PDS_JUNGFRAU_DDL_H
