
// *** Do not edit this file, it is auto-generated ***

#include "pdsdata/psddl/cspad2x2.ddl.h"

#include <iostream>
namespace Pds {
namespace CsPad2x2 {
CsPad2x2DigitalPotsCfg::CsPad2x2DigitalPotsCfg(const uint8_t* arg__pots)
{
  if (arg__pots) std::copy(arg__pots, arg__pots+(80), &_pots[0]);
}
CsPad2x2GainMapCfg::CsPad2x2GainMapCfg(const uint16_t* arg__gainMap)
{
  if (arg__gainMap) std::copy(arg__gainMap, arg__gainMap+(35890), &_gainMap[0][0]);
}
uint32_t
ConfigV1::numAsicsRead() const {
  return 4;
}
uint32_t
ConfigV1::numAsicsStored() const {
  return __builtin_popcount(this->roiMask())*2;
}
uint32_t
ConfigV2::numAsicsRead() const {
  return 4;
}
uint32_t
ConfigV2::numAsicsStored() const {
  return __builtin_popcount(this->roiMask())*2;
}
float
ElementV1::common_mode(uint32_t section) const {
  return 0;
}
} // namespace CsPad2x2
} // namespace Pds
