
// *** Do not edit this file, it is auto-generated ***

#include "pdsdata/psddl/tprds.ddl.h"

#include <iostream>
namespace Pds {
namespace TprDSData {
ConfigV1::ConfigV1(uint32_t arg__dataSize, uint32_t arg__fullThreshold)
    : _dataSize(arg__dataSize), _fullThreshold(arg__fullThreshold)
{
}
} // namespace TprDSData
} // namespace Pds
